/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pricing Alerts
         * @description Changes found between two snapshots of a tracked pricing page, newest first.
         */
        get: operations["list_pricing_alerts_pricing_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Every run, newest first.
         */
        get: operations["list_runs_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Create a run and queue it. It stops at the first checkpoint.
         */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description A run with the status of each stage. `paused_quota` is a pause, not a failure.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Approve the open checkpoint, unchanged or edited, and queue the rest of the run.
         */
        post: operations["approve_runs__run_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Changelog Alerts
         * @description What competitors shipped that touches this run: fixes for its pain points, and
         *     new features its PRD does not cover. Matching is done by `changelog match`.
         */
        get: operations["get_changelog_alerts_runs__run_id__changelog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/exports/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Export
         * @description The pain-point report, the PRD or the task plan, as Markdown or JSON.
         */
        get: operations["download_export_runs__run_id__exports__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume
         * @description Queue a paused or failed run again, or run it again from a named stage.
         */
        post: operations["resume_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stages/{stage_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stage Output */
        get: operations["get_stage_output_runs__run_id__stages__stage_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptanceCriteria */
        AcceptanceCriteria: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Tasks */
            tasks: components["schemas"]["TaskCriteria"][];
        };
        /**
         * AlertKind
         * @enum {string}
         */
        AlertKind: "shipped_fix" | "unplanned_feature";
        /**
         * Approve
         * @description Approve the checkpoint as it is, with a whole edited output, or with edits.
         */
        Approve: {
            competitors?: components["schemas"]["CompetitorEdits"] | null;
            /** Edited Output */
            edited_output?: {
                [key: string]: unknown;
            } | null;
            pain_points?: components["schemas"]["PainPointEdits"] | null;
        };
        /**
         * BillingPeriod
         * @enum {string}
         */
        BillingPeriod: "month" | "year" | "one_time";
        /**
         * ChangeKind
         * @enum {string}
         */
        ChangeKind: "price_increased" | "price_decreased" | "price_added" | "price_removed" | "plan_added" | "plan_removed" | "limits_changed";
        /** ChangelogAlert */
        ChangelogAlert: {
            /**
             * Cluster Ids
             * @default []
             */
            cluster_ids: string[];
            /**
             * Follow Ups
             * @default {}
             */
            follow_ups: {
                [key: string]: components["schemas"]["FollowUp"];
            };
            item: components["schemas"]["ChangelogItem"];
            kind: components["schemas"]["AlertKind"];
            /**
             * Pain Point Labels
             * @default []
             */
            pain_point_labels: string[];
            /** Product Name */
            product_name: string;
            /** Reason */
            reason: string;
            /**
             * Requirement Ids
             * @default []
             */
            requirement_ids: string[];
        };
        /** ChangelogAlerts */
        ChangelogAlerts: {
            /** Alerts */
            alerts: components["schemas"]["ChangelogAlert"][];
            /** Items Matched */
            items_matched: number;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** ChangelogItem */
        ChangelogItem: {
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Id */
            id: string;
            /** Product Id */
            product_id: string;
            /** Released At */
            released_at?: string | null;
            source: components["schemas"]["ChangelogSourceKind"];
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Version */
            version?: string | null;
        };
        /**
         * ChangelogSourceKind
         * @enum {string}
         */
        ChangelogSourceKind: "github" | "feed" | "page" | "app_store" | "google_play";
        /** Competitor */
        Competitor: {
            /** Id */
            id: string;
            /**
             * Is Incumbent
             * @default false
             */
            is_incumbent: boolean;
            /** Name */
            name: string;
            /** Positioning */
            positioning: string;
            /** Reason */
            reason: string;
            /**
             * @default {
             *       "app_store": null,
             *       "google_play": null
             *     }
             */
            store_ids: components["schemas"]["StoreIds"];
            /** Target Users */
            target_users: string;
            /** Url */
            url: string;
        };
        /** CompetitorEdits */
        CompetitorEdits: {
            /**
             * Add
             * @default []
             */
            add: {
                [key: string]: unknown;
            }[];
            /**
             * Remove
             * @default []
             */
            remove: string[];
        };
        /** CompetitorList */
        CompetitorList: {
            /** Competitors */
            competitors: components["schemas"]["Competitor"][];
            /**
             * Rejected
             * @default []
             */
            rejected: components["schemas"]["RejectedCandidate"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** CreateRun */
        CreateRun: {
            input: components["schemas"]["RunInput"];
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** Criterion */
        Criterion: {
            /** Given */
            given: string;
            kind: components["schemas"]["CriterionKind"];
            /** Then */
            then: string;
            /** When */
            when: string;
        };
        /**
         * CriterionKind
         * @enum {string}
         */
        CriterionKind: "happy_path" | "edge_case" | "failure_state";
        /**
         * Effort
         * @description A fixed scale for one developer. Anything larger than XL is split into tasks.
         * @enum {string}
         */
        Effort: "XS" | "S" | "M" | "L" | "XL";
        /** Epic */
        Epic: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Tasks */
            tasks: components["schemas"]["Task"][];
            /** Title */
            title: string;
        };
        /**
         * FollowUp
         * @description A pain point's share of all reviews before and after a release.
         */
        FollowUp: {
            /** Change */
            change?: number | null;
            /** Months */
            months: number;
            /** Share After */
            share_after?: number | null;
            /** Share Before */
            share_before?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** Incumbent */
        Incumbent: {
            /** Name */
            name: string;
            /**
             * @default {
             *       "app_store": null,
             *       "google_play": null
             *     }
             */
            store_ids: components["schemas"]["StoreIds"];
            /**
             * Urls
             * @default []
             */
            urls: string[];
        };
        /** JunkCluster */
        JunkCluster: {
            /** Cluster Id */
            cluster_id: string;
            /** Reason */
            reason: string;
            /** Review Count */
            review_count: number;
        };
        /** LanguageCounts */
        LanguageCounts: {
            /** English */
            english: number;
            /** Hinglish */
            hinglish: number;
            /** Not Analysed */
            not_analysed: number;
        };
        /**
         * MarketGap
         * @description A fact about a competitor that a requirement can cite.
         *
         *     Until the market panel exists (phase 21), the only such fact is what stage 1
         *     recorded about the competitor.
         */
        MarketGap: {
            /** Fact */
            fact: string;
            /** Id */
            id: string;
            /** Product Id */
            product_id: string;
            /** Product Name */
            product_name: string;
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "new_idea" | "alternative" | "new_feature";
        /** PainPoint */
        PainPoint: {
            /** Cluster Id */
            cluster_id: string;
            /** Description */
            description: string;
            /** Label */
            label: string;
            /**
             * Merged Cluster Ids
             * @default []
             */
            merged_cluster_ids: string[];
            /** Negative Share */
            negative_share: number;
            /** Product Ids */
            product_ids: string[];
            /**
             * Quote Glosses
             * @default {}
             */
            quote_glosses: {
                [key: string]: string;
            };
            /** Quote Review Ids */
            quote_review_ids: string[];
            /** Rank */
            rank: number;
            /** Review Count */
            review_count: number;
            /** Score */
            score: number;
            /** Severity */
            severity: number;
            /** Severity Reason */
            severity_reason: string;
            /**
             * Switching Review Ids
             * @default []
             */
            switching_review_ids: string[];
            trend: components["schemas"]["Trend"];
        };
        /**
         * PainPointEdits
         * @description Pain points are named by their rank in the stage's output, or by cluster id.
         */
        PainPointEdits: {
            /**
             * Drop
             * @default []
             */
            drop: string[];
            /**
             * Merge
             * @default []
             */
            merge: string[][];
            /**
             * Rank
             * @default []
             */
            rank: string[];
            /**
             * Rename
             * @default {}
             */
            rename: {
                [key: string]: string;
            };
        };
        /** PainPointReport */
        PainPointReport: {
            /** Clustered Reviews */
            clustered_reviews: number;
            /**
             * Junk Clusters
             * @default []
             */
            junk_clusters: components["schemas"]["JunkCluster"][];
            language_counts: components["schemas"]["LanguageCounts"];
            /** Noise Reviews */
            noise_reviews: number;
            /** Pain Points */
            pain_points: components["schemas"]["PainPoint"][];
            /** Ranking Formula */
            ranking_formula: string;
            /**
             * Schema Version
             * @default 3
             * @constant
             */
            schema_version: 3;
            /**
             * Switching Reviews
             * @default []
             */
            switching_reviews: components["schemas"]["SwitchingReview"][];
            /**
             * Switching Table
             * @default []
             */
            switching_table: components["schemas"]["SwitchingRow"][];
            trend_settings: components["schemas"]["TrendSettings"];
        };
        /** Plan */
        Plan: {
            /**
             * Contact Sales
             * @default false
             */
            contact_sales: boolean;
            /**
             * Features
             * @default []
             */
            features: string[];
            /**
             * Is Free
             * @default false
             */
            is_free: boolean;
            /**
             * Limits
             * @default []
             */
            limits: string[];
            /** Name */
            name: string;
            /**
             * Prices
             * @default []
             */
            prices: components["schemas"]["Price"][];
        };
        /**
         * Platform
         * @enum {string}
         */
        Platform: "android" | "ios" | "web";
        /** Prd */
        Prd: {
            /** Goals */
            goals: string[];
            /**
             * Market Gaps
             * @default []
             */
            market_gaps: components["schemas"]["MarketGap"][];
            /**
             * Non Goals
             * @default []
             */
            non_goals: string[];
            /** Problem */
            problem: string;
            /** Requirements */
            requirements: components["schemas"]["Requirement"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Success Metrics */
            success_metrics: string[];
            /** Users */
            users: string;
        };
        /** Price */
        Price: {
            /** Amount */
            amount: number | string;
            /**
             * Billed Annually
             * @default false
             */
            billed_annually: boolean;
            /** Currency */
            currency: string;
            /**
             * Per Seat
             * @default false
             */
            per_seat: boolean;
            period: components["schemas"]["BillingPeriod"];
        };
        /**
         * PricingAlert
         * @description A pricing page that changed between two snapshots, and how.
         */
        PricingAlert: {
            /** Changes */
            changes: components["schemas"]["PricingChange"][];
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /**
             * Previous Fetched At
             * Format: date-time
             */
            previous_fetched_at: string;
            /** Product Id */
            product_id: string;
            /** Product Name */
            product_name: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Url */
            url: string;
        };
        /** PricingChange */
        PricingChange: {
            /**
             * Billed Annually
             * @default false
             */
            billed_annually: boolean;
            /** Currency */
            currency?: string | null;
            kind: components["schemas"]["ChangeKind"];
            /** New Amount */
            new_amount?: string | null;
            /**
             * New Limits
             * @default []
             */
            new_limits: string[];
            /** Old Amount */
            old_amount?: string | null;
            /**
             * Old Limits
             * @default []
             */
            old_limits: string[];
            period?: components["schemas"]["BillingPeriod"] | null;
            /** Plan */
            plan: string;
        };
        /** PricingSnapshot */
        PricingSnapshot: {
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Free Tier */
            free_tier: boolean;
            /** Free Trial */
            free_trial: boolean;
            /** Plans */
            plans: components["schemas"]["Plan"][];
            /** Product Id */
            product_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Text Hash */
            text_hash: string;
            /**
             * Trial Days
             * @default null
             */
            trial_days: number | null;
            /** Url */
            url: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "must" | "should" | "could";
        /** Problem */
        Problem: {
            /** Detail */
            detail: string;
        };
        /** ProductReviewCounts */
        ProductReviewCounts: {
            /** By Language */
            by_language: {
                [key: string]: number;
            };
            /** By Sentiment */
            by_sentiment: {
                [key: string]: number;
            };
            /** By Source */
            by_source: {
                [key: string]: number;
            };
            /**
             * Not Analysed
             * @default 0
             */
            not_analysed: number;
            /** Product Id */
            product_id: string;
            /** Total */
            total: number;
        };
        /** RejectedCandidate */
        RejectedCandidate: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /**
             * Url
             * @default null
             */
            url: string | null;
        };
        /** Requirement */
        Requirement: {
            /** Evidence */
            evidence: string[];
            /** Id */
            id: string;
            priority: components["schemas"]["Priority"];
            /** Statement */
            statement: string;
        };
        /** Resume */
        Resume: {
            /** From Stage */
            from_stage?: string | null;
        };
        /** ReviewSet */
        ReviewSet: {
            /**
             * Dropped
             * @default {}
             */
            dropped: {
                [key: string]: number;
            };
            /** Products */
            products: components["schemas"]["ProductReviewCounts"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * ReviewSourceName
         * @enum {string}
         */
        ReviewSourceName: "google_play" | "app_store" | "reddit" | "product_hunt";
        /** Roadmap */
        Roadmap: {
            /** Items */
            items: components["schemas"]["RoadmapItem"][];
            /**
             * Ordering
             * @default prd_order
             * @constant
             */
            ordering: "prd_order";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** RoadmapItem */
        RoadmapItem: {
            /** Rank */
            rank: number;
            /** Requirement Id */
            requirement_id: string;
            /** Task Ids */
            task_ids: string[];
        };
        /** RunInput */
        RunInput: {
            /** Idea */
            idea: string;
            /** @default null */
            incumbent: components["schemas"]["Incumbent"] | null;
            /**
             * Known Competitors
             * @default []
             */
            known_competitors: string[];
            mode: components["schemas"]["Mode"];
            /** Platforms */
            platforms: components["schemas"]["Platform"][];
            /** Region */
            region: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Target Users */
            target_users: string;
            /**
             * Tech Stack
             * @default []
             */
            tech_stack: string[];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "awaiting_approval" | "paused_quota" | "failed" | "completed";
        /** RunSummary */
        RunSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Idea */
            idea: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunView */
        RunView: {
            /** Awaiting Approval */
            awaiting_approval: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Idea */
            idea: string;
            input: components["schemas"]["RunInput"];
            /** Pause Reason */
            pause_reason: string | null;
            /** Seed */
            seed: number;
            /** Stages */
            stages: components["schemas"]["StageView"][];
            status: components["schemas"]["RunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Sentiment
         * @enum {string}
         */
        Sentiment: "positive" | "neutral" | "mixed" | "negative";
        /** StageOutputView */
        StageOutputView: {
            /** Edited */
            edited: boolean;
            /** Key */
            key: string;
            /** Original Output */
            original_output: {
                [key: string]: unknown;
            } | null;
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Schema Version */
            schema_version: number | null;
            status: components["schemas"]["StageStatus"];
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "pending" | "running" | "awaiting_approval" | "failed" | "completed";
        /** StageView */
        StageView: {
            /** Approved At */
            approved_at: string | null;
            /** Checkpoint */
            checkpoint: boolean;
            /** Edited */
            edited: boolean;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Has Output */
            has_output: boolean;
            /** Key */
            key: string;
            /** Number */
            number: number | null;
            /** Schema Version */
            schema_version: number | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["StageStatus"];
        };
        /** StoreIds */
        StoreIds: {
            /**
             * App Store
             * @default null
             */
            app_store: string | null;
            /**
             * Google Play
             * @default null
             */
            google_play: string | null;
        };
        /**
         * SwitchingIntent
         * @description What a review says about switching, seen from the product it reviews.
         * @enum {string}
         */
        SwitchingIntent: "leaving" | "switched_to" | "switched_from" | "considering";
        /** SwitchingReview */
        SwitchingReview: {
            intent: components["schemas"]["SwitchingIntent"];
            /**
             * Other Product
             * @default null
             */
            other_product: string | null;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /** Review Id */
            review_id: string;
        };
        /**
         * SwitchingRow
         * @description One line of the switching table: reviews that moved, or may move, the same way.
         */
        SwitchingRow: {
            /** Count */
            count: number;
            /** From Product */
            from_product: string | null;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Review Ids */
            review_ids: string[];
            /** To Product */
            to_product: string | null;
        };
        /** Task */
        Task: {
            /**
             * Depends On
             * @default []
             */
            depends_on: string[];
            /** Description */
            description: string;
            effort: components["schemas"]["Effort"];
            /** Id */
            id: string;
            /** Requirement Ids */
            requirement_ids: string[];
            /** Title */
            title: string;
        };
        /** TaskCriteria */
        TaskCriteria: {
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
            /** Task Id */
            task_id: string;
        };
        /** TaskPlan */
        TaskPlan: {
            /** Epics */
            epics: components["schemas"]["Epic"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /**
         * Trend
         * @description The pain point's monthly share of all reviews, and whether it is growing.
         *
         *     Shares, not raw counts: a release that doubles the reviews doubles every count.
         */
        Trend: {
            /**
             * Growth
             * @default null
             */
            growth: number | null;
            /** Months */
            months: components["schemas"]["TrendPoint"][];
            /**
             * Previous Share
             * @default null
             */
            previous_share: number | null;
            /**
             * Recent Share
             * @default null
             */
            recent_share: number | null;
            /**
             * Rising
             * @default false
             */
            rising: boolean;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Enough */
            enough: boolean;
            /** Month */
            month: string;
            /** Reviews */
            reviews: number;
            /** Total Reviews */
            total_reviews: number;
        };
        /**
         * TrendSettings
         * @description How trends were computed. Kept in the report so an edit recomputes them the same way.
         */
        TrendSettings: {
            /** Min Month Reviews */
            min_month_reviews: number;
            /** Min Window Reviews */
            min_window_reviews: number;
            /** Months */
            months: number;
            /** Rising Threshold */
            rising_threshold: number;
            /** Window Months */
            window_months: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_pricing_alerts_pricing_alerts_get: {
        parameters: {
            query?: {
                product_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingAlert"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    approve_runs__run_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Approve"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_changelog_alerts_runs__run_id__changelog_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangelogAlerts"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    download_export_runs__run_id__exports__name__get: {
        parameters: {
            query?: {
                format?: "md" | "json";
            };
            header?: never;
            path: {
                run_id: string;
                name: "report" | "prd" | "tasks";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resume_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Resume"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_stage_output_runs__run_id__stages__stage_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                stage_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageOutputView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
